# -*- coding: utf-8 -*-
"""multiplication tables.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R2OK8UbKTAuNQE4ujj1zEoeNQh6t2o6e
"""

#tables
n=int(input())
for i in range(1,n+1):
  for j in range(1,11):
    print(i,"x",j,"=",i*j)

